"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { supabase } from "@/lib/supabase";
import {
  getAssignedCar,
  getUserRole,
  hasPermission,
} from "@/lib/userAccess";
import LogoutButton from "@/app/components/LogoutButton";

type PostEventForm = {
  chassis: string;
  driver: string;
  engine_no: string;
  hours_remaining: string;
  gearbox_no: string;
  fuel_drained_kg: string;
  front_ride_height: string;
  rear_ride_height: string;
  diff_break_off: string;
  diff_dynamic: string;
  notes: string;
};

const EMPTY_FORM: PostEventForm = {
  chassis: "",
  driver: "",
  engine_no: "",
  hours_remaining: "",
  gearbox_no: "",
  fuel_drained_kg: "",
  front_ride_height: "",
  rear_ride_height: "",
  diff_break_off: "",
  diff_dynamic: "",
  notes: "",
};

async function generatePostEventPdf({
  carId,
  form,
  userEmail,
}: {
  carId: number;
  form: PostEventForm;
  userEmail: string;
}) {
  const pdfDoc = await PDFDocument.create();

  const page = pdfDoc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();

  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const red = rgb(0.72, 0.11, 0.11);
  const dark = rgb(0.08, 0.09, 0.1);
  const grey = rgb(0.35, 0.35, 0.35);

  let y = height - 60;

  function drawText(
    text: string,
    x: number,
    yPos: number,
    size = 11,
    font = regularFont,
    colour = dark,
  ) {
    page.drawText(text || "-", {
      x,
      y: yPos,
      size,
      font,
      color: colour,
    });
  }

  function drawField(label: string, value: string, x: number, yPos: number) {
    drawText(label.toUpperCase(), x, yPos, 8, boldFont, grey);

    page.drawRectangle({
      x,
      y: yPos - 34,
      width: 245,
      height: 26,
      borderColor: rgb(0.75, 0.75, 0.75),
      borderWidth: 1,
    });

    drawText(value || "-", x + 8, yPos - 26, 11, regularFont, dark);
  }

  page.drawRectangle({
    x: 0,
    y: height - 90,
    width,
    height: 90,
    color: rgb(0.06, 0.07, 0.08),
  });

  drawText("RODIN MOTORSPORT", 40, height - 35, 10, boldFont, red);
  drawText(
    `Car ${carId} Post-Event Sheet`,
    40,
    height - 62,
    24,
    boldFont,
    rgb(1, 1, 1),
  );

  drawText(
    `Generated: ${new Date().toLocaleString("en-GB")}`,
    40,
    height - 82,
    9,
    regularFont,
    rgb(0.75, 0.75, 0.75),
  );

  y -= 120;

  drawField("Chassis", form.chassis, 40, y);
  drawField("Driver", form.driver, 310, y);

  y -= 70;

  drawField("Engine No.", form.engine_no, 40, y);
  drawField("Hours Remaining", form.hours_remaining, 310, y);

  y -= 70;

  drawField("Gearbox No.", form.gearbox_no, 40, y);
  drawField("Fuel Drained KG", form.fuel_drained_kg, 310, y);

  y -= 70;

  drawField("Front Ride Height", form.front_ride_height, 40, y);
  drawField("Rear Ride Height", form.rear_ride_height, 310, y);

  y -= 70;

  drawField("Diff Break-Off", form.diff_break_off, 40, y);
  drawField("Diff Dynamic", form.diff_dynamic, 310, y);

  y -= 80;

  drawText("NOTES", 40, y, 9, boldFont, grey);

  page.drawRectangle({
    x: 40,
    y: y - 145,
    width: 515,
    height: 130,
    borderColor: rgb(0.75, 0.75, 0.75),
    borderWidth: 1,
  });

  const notes = form.notes || "-";
  const maxCharsPerLine = 85;
  const noteLines = notes.match(new RegExp(`.{1,${maxCharsPerLine}}`, "g")) ?? [
    "-",
  ];

  let noteY = y - 35;

  noteLines.slice(0, 7).forEach((line) => {
    drawText(line, 52, noteY, 10, regularFont, dark);
    noteY -= 16;
  });

  y -= 190;

  drawText("Created By", 40, y, 9, boldFont, grey);
  drawText(userEmail || "Unknown", 40, y - 18, 10, regularFont, dark);

  drawText("Car ID", 310, y, 9, boldFont, grey);
  drawText(String(carId), 310, y - 18, 10, regularFont, dark);

  page.drawLine({
    start: { x: 40, y: 70 },
    end: { x: 555, y: 70 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });

  drawText(
    "Post-event sheet generated by Rodin Motorsport Mechanics Hub",
    40,
    50,
    8,
    regularFont,
    grey,
  );

  return pdfDoc.save();
}

export default function PostEventSheetPage() {
  const params = useParams();
  const router = useRouter();

  const carId = Number(params.carId);

  const [form, setForm] = useState<PostEventForm>(EMPTY_FORM);
  const [userEmail, setUserEmail] = useState("");
  const [saving, setSaving] = useState(false);
  const [loadingLatest, setLoadingLatest] = useState(true);
  const [canEditPostEvent, setCanEditPostEvent] = useState(false);

  const [message, setMessage] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  const completionPercent = useMemo(() => {
    const requiredFields = [
      form.chassis,
      form.driver,
      form.engine_no,
      form.hours_remaining,
      form.gearbox_no,
      form.fuel_drained_kg,
      form.front_ride_height,
      form.rear_ride_height,
      form.diff_break_off,
      form.diff_dynamic,
    ];

    const filled = requiredFields.filter((value) => value.trim()).length;
    return Math.round((filled / requiredFields.length) * 100);
  }, [form]);

  async function checkAccess() {
    if (!Number.isFinite(carId)) {
      router.replace("/login");
      return null;
    }

    const { data: userData, error: userError } = await supabase.auth.getUser();

    if (userError || !userData.user?.email) {
      router.replace("/login");
      return null;
    }

    const email = userData.user.email.trim().toLowerCase();
    const role = getUserRole(email);
    const assignedCar = getAssignedCar(email);

    if (role === "number2_mechanic") {
      router.replace("/team-jobs");
      return null;
    }

    if (!hasPermission(email, "post_event:view")) {
      router.replace("/login");
      return null;
    }

    if (role === "number1_mechanic") {
      if (!assignedCar) {
        router.replace("/login");
        return null;
      }

      if (Number(assignedCar) !== carId) {
        router.replace(`/car/${assignedCar}/post-event`);
        return null;
      }
    }

    setCanEditPostEvent(hasPermission(email, "post_event:edit"));
    setUserEmail(email);

    return email;
  }

  useEffect(() => {
    async function init() {
      if (!carId) return;

      setLoadingLatest(true);
      setErrorMessage("");

      const email = await checkAccess();

      if (!email) {
        return;
      }

      const { data, error } = await supabase
        .from("post_event_sheets")
        .select("*")
        .eq("car_id", carId)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      if (error) {
        setErrorMessage(error.message);
        setLoadingLatest(false);
        return;
      }

      if (data) {
        setForm({
          chassis: String(data.chassis ?? ""),
          driver: String(data.driver ?? ""),
          engine_no: String(data.engine_no ?? ""),
          hours_remaining: String(data.hours_remaining ?? ""),
          gearbox_no: String(data.gearbox_no ?? ""),
          fuel_drained_kg: String(data.fuel_drained_kg ?? ""),
          front_ride_height: String(data.front_ride_height ?? ""),
          rear_ride_height: String(data.rear_ride_height ?? ""),
          diff_break_off: String(data.diff_break_off ?? ""),
          diff_dynamic: String(data.diff_dynamic ?? ""),
          notes: String(data.notes ?? ""),
        });
      }

      setLoadingLatest(false);
    }

    init();

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [carId]);

  function updateField(field: keyof PostEventForm, value: string) {
    setForm((current) => ({
      ...current,
      [field]: value,
    }));
  }

  async function saveSheet() {
    if (!canEditPostEvent) {
      setErrorMessage("You do not have permission to save post-event sheets.");
      return;
    }

    setSaving(true);
    setMessage("");
    setErrorMessage("");

    try {
      const email = await checkAccess();

      if (!email) {
        setSaving(false);
        return;
      }

      const pdfBytes = await generatePostEventPdf({
        carId,
        form,
        userEmail: email,
      });

      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");

      const pdfFilename = `car-${carId}-post-event-${timestamp}.pdf`;
      const pdfPath = `car-${carId}/${pdfFilename}`;

      const { error: uploadError } = await supabase.storage
        .from("post-event-sheets")
        .upload(pdfPath, pdfBytes, {
          contentType: "application/pdf",
          upsert: false,
        });

      if (uploadError) {
        throw new Error(uploadError.message);
      }

      const { error: insertError } = await supabase
        .from("post_event_sheets")
        .insert({
          car_id: carId,
          chassis: form.chassis.trim(),
          driver: form.driver.trim(),
          engine_no: form.engine_no.trim(),
          hours_remaining: form.hours_remaining.trim(),
          gearbox_no: form.gearbox_no.trim(),
          fuel_drained_kg: form.fuel_drained_kg.trim(),
          front_ride_height: form.front_ride_height.trim(),
          rear_ride_height: form.rear_ride_height.trim(),
          diff_break_off: form.diff_break_off.trim(),
          diff_dynamic: form.diff_dynamic.trim(),
          notes: form.notes.trim(),
          created_by: email || null,
          created_at: new Date().toISOString(),
          pdf_path: pdfPath,
          pdf_filename: pdfFilename,
        });

      if (insertError) {
        throw new Error(insertError.message);
      }

      setMessage("Post-event sheet saved as a PDF successfully.");
    } catch (error) {
      setErrorMessage(
        error instanceof Error
          ? error.message
          : "Failed to save post-event PDF.",
      );
    }

    setSaving(false);
  }

  function clearForm() {
    if (!canEditPostEvent) {
      setErrorMessage("You do not have permission to clear this form.");
      return;
    }

    const confirmed = window.confirm(
      "Clear the current post-event sheet on screen? This will not delete saved records.",
    );

    if (!confirmed) return;

    setForm(EMPTY_FORM);
    setMessage("");
    setErrorMessage("");
  }

  if (loadingLatest) {
    return (
      <main className="min-h-screen bg-[#0d0f12] p-6 text-zinc-100">
        <div className="rounded-3xl border border-zinc-800 bg-[#14181d] p-6">
          Loading post-event sheet...
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#0d0f12] p-6 text-zinc-100">
      <header className="mb-8 flex flex-wrap items-start justify-between gap-4 rounded-3xl border border-zinc-800 bg-[#14181d] p-6 shadow-xl">
        <div>
          <p className="text-xs uppercase tracking-[0.35em] text-red-400">
            Rodin Motorsport
          </p>

          <h1 className="mt-3 text-4xl font-semibold tracking-tight">
            Car {carId} Post-Event Sheet
          </h1>

          <p className="mt-3 max-w-3xl text-sm text-zinc-400">
            Record the key post-event details for chassis, engine, gearbox, fuel
            drained, ride heights and diff checks.
          </p>

          {!canEditPostEvent && (
            <p className="mt-4 rounded-xl border border-yellow-800 bg-yellow-950/30 px-4 py-3 text-sm text-yellow-200">
              Your login can view this sheet, but cannot save or edit
              post-event records.
            </p>
          )}
        </div>

        <LogoutButton />
      </header>

      {message && (
        <div className="mb-6 rounded-2xl border border-green-800 bg-green-950/20 p-4 text-sm text-green-300">
          {message}
        </div>
      )}

      {errorMessage && (
        <div className="mb-6 rounded-2xl border border-red-900 bg-red-950/40 p-4 text-sm text-red-200">
          {errorMessage}
        </div>
      )}

      <section className="mb-6 grid gap-6 lg:grid-cols-[1fr_320px]">
        <div className="rounded-3xl border border-zinc-800 bg-[#14181d] p-6 shadow-xl">
          <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
            <div>
              <h2 className="text-2xl font-semibold">Event Details</h2>

              <p className="mt-1 text-sm text-zinc-500">
                Main post-event identity and running details.
              </p>
            </div>

            <div className="rounded-2xl border border-zinc-700 bg-[#0d0f12] px-5 py-3 text-right">
              <p className="text-xs uppercase tracking-[0.25em] text-zinc-500">
                Complete
              </p>

              <p className="text-2xl font-semibold text-red-400">
                {completionPercent}%
              </p>
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
            <InputCard
              label="Chassis"
              value={form.chassis}
              placeholder="#022"
              disabled={!canEditPostEvent}
              onChange={(value) => updateField("chassis", value)}
            />

            <InputCard
              label="Driver"
              value={form.driver}
              placeholder="M. Rehm"
              disabled={!canEditPostEvent}
              onChange={(value) => updateField("driver", value)}
            />

            <InputCard
              label="Engine No."
              value={form.engine_no}
              placeholder="Engine number"
              disabled={!canEditPostEvent}
              onChange={(value) => updateField("engine_no", value)}
            />

            <InputCard
              label="Hours Remaining"
              value={form.hours_remaining}
              placeholder="0.0"
              disabled={!canEditPostEvent}
              onChange={(value) => updateField("hours_remaining", value)}
            />

            <InputCard
              label="Gearbox No."
              value={form.gearbox_no}
              placeholder="Gearbox number"
              disabled={!canEditPostEvent}
              onChange={(value) => updateField("gearbox_no", value)}
            />
          </div>
        </div>

        <div className="rounded-3xl border border-red-900/40 bg-[#181315] p-6 shadow-xl">
          <p className="text-xs uppercase tracking-[0.3em] text-red-300">
            Sheet Status
          </p>

          <div className="mt-6 h-3 overflow-hidden rounded-full bg-red-950/50">
            <div
              className="h-full rounded-full bg-red-600 transition-all"
              style={{ width: `${completionPercent}%` }}
            />
          </div>

          <p className="mt-4 text-sm text-zinc-400">
            Fill in the fields, then save the sheet. Each save creates a new
            timestamped post-event record.
          </p>

          <div className="mt-6 rounded-2xl border border-red-900/50 bg-[#0d0f12] p-4 text-sm text-zinc-400">
            <p>
              Car:{" "}
              <span className="font-semibold text-zinc-100">Car {carId}</span>
            </p>

            <p className="mt-1">
              User:{" "}
              <span className="font-semibold text-zinc-100">
                {userEmail || "Unknown"}
              </span>
            </p>
          </div>
        </div>
      </section>

      <section className="mb-6 grid gap-6 lg:grid-cols-3">
        <div className="rounded-3xl border border-zinc-800 bg-[#14181d] p-6 shadow-xl">
          <div className="mb-5">
            <p className="text-xs uppercase tracking-[0.3em] text-red-400">
              Fuel
            </p>

            <h2 className="mt-2 text-2xl font-semibold">Fuel Drained</h2>
          </div>

          <div className="rounded-2xl border border-zinc-800 bg-[#0d0f12] p-5">
            <label className="block text-sm font-semibold text-zinc-300">
              Fuel Drained
            </label>

            <div className="mt-3 flex items-end gap-3">
              <input
                value={form.fuel_drained_kg}
                onChange={(event) =>
                  updateField("fuel_drained_kg", event.target.value)
                }
                disabled={!canEditPostEvent}
                placeholder="0.00"
                inputMode="decimal"
                className="w-full rounded-xl border border-zinc-700 bg-[#111418] px-4 py-4 text-3xl font-semibold text-zinc-100 outline-none transition focus:border-red-500 disabled:cursor-not-allowed disabled:opacity-50"
              />

              <span className="pb-4 text-sm font-semibold uppercase tracking-widest text-zinc-500">
                KG
              </span>
            </div>
          </div>
        </div>

        <div className="rounded-3xl border border-zinc-800 bg-[#14181d] p-6 shadow-xl lg:col-span-2">
          <div className="mb-5">
            <p className="text-xs uppercase tracking-[0.3em] text-red-400">
              Platform
            </p>

            <h2 className="mt-2 text-2xl font-semibold">Ride Heights</h2>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <InputCard
              label="Front Ride Height"
              value={form.front_ride_height}
              placeholder="Front ride height"
              disabled={!canEditPostEvent}
              onChange={(value) => updateField("front_ride_height", value)}
            />

            <InputCard
              label="Rear Ride Height"
              value={form.rear_ride_height}
              placeholder="Rear ride height"
              disabled={!canEditPostEvent}
              onChange={(value) => updateField("rear_ride_height", value)}
            />
          </div>
        </div>
      </section>

      <section className="mb-6 rounded-3xl border border-zinc-800 bg-[#14181d] p-6 shadow-xl">
        <div className="mb-5">
          <p className="text-xs uppercase tracking-[0.3em] text-red-400">
            Differential
          </p>

          <h2 className="mt-2 text-2xl font-semibold">Diff Checks</h2>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <InputCard
            label="Diff Break-Off"
            value={form.diff_break_off}
            placeholder="Value / comment"
            disabled={!canEditPostEvent}
            onChange={(value) => updateField("diff_break_off", value)}
          />

          <InputCard
            label="Diff Dynamic"
            value={form.diff_dynamic}
            placeholder="Value / comment"
            disabled={!canEditPostEvent}
            onChange={(value) => updateField("diff_dynamic", value)}
          />
        </div>
      </section>

      <section className="mb-6 rounded-3xl border border-zinc-800 bg-[#14181d] p-6 shadow-xl">
        <h2 className="text-2xl font-semibold">Notes</h2>

        <p className="mt-1 text-sm text-zinc-500">
          Add any extra comments, damage notes, mechanic observations or
          follow-up actions.
        </p>

        <textarea
          value={form.notes}
          onChange={(event) => updateField("notes", event.target.value)}
          disabled={!canEditPostEvent}
          placeholder="Type post-event notes here..."
          rows={6}
          className="mt-5 w-full resize-none rounded-2xl border border-zinc-700 bg-[#0d0f12] px-4 py-4 text-sm text-zinc-100 outline-none transition focus:border-red-500 disabled:cursor-not-allowed disabled:opacity-50"
        />
      </section>

      <section className="rounded-3xl border border-zinc-800 bg-[#14181d] p-6 shadow-xl">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-semibold">Save Sheet</h2>

            <p className="mt-1 text-sm text-zinc-500">
              Saves this as a new post-event sheet record for Car {carId}.
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <button
              type="button"
              onClick={clearForm}
              disabled={!canEditPostEvent}
              className="rounded-xl border border-zinc-700 px-5 py-3 text-sm font-semibold text-zinc-300 hover:border-red-500 hover:text-red-300 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Clear Form
            </button>

            <button
              type="button"
              onClick={saveSheet}
              disabled={saving || !canEditPostEvent}
              className="rounded-xl bg-red-700 px-6 py-3 text-sm font-semibold text-white hover:bg-red-600 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {saving ? "Saving..." : "Save Post-Event Sheet"}
            </button>
          </div>
        </div>
      </section>
    </main>
  );
}

function InputCard({
  label,
  value,
  placeholder,
  disabled,
  onChange,
}: {
  label: string;
  value: string;
  placeholder: string;
  disabled?: boolean;
  onChange: (value: string) => void;
}) {
  return (
    <label className="block rounded-2xl border border-zinc-800 bg-[#0d0f12] p-4">
      <span className="text-xs font-semibold uppercase tracking-[0.22em] text-zinc-500">
        {label}
      </span>

      <input
        value={value}
        onChange={(event) => onChange(event.target.value)}
        placeholder={placeholder}
        disabled={disabled}
        className="mt-3 w-full border-none bg-transparent text-lg font-semibold text-zinc-100 outline-none placeholder:text-zinc-700 disabled:cursor-not-allowed disabled:opacity-50"
      />
    </label>
  );
}